### ISSUE TITLE
Version 2 roadmap

### ISSUE THREAD

**Issue by yrccondor** [yrccondor/mdx#28]
Version 2 will release in few months, including following changes:

- [x] Material Design 2 support
- [x] Remove jQuery
- [x] Improved performence
- [x] Improved style in desktop
- [x] New LazyLoad style
- [x] Gutenberg support
- [x] Archive page
- [x] English support
- [x] Table of contents in posts
- [x] New clean styles
- [x] Better footer
- [x] Ad settings
- [x] Always-Dark mode
- [x] ~~New "Creative" home page style~~ (delayed to 2.0.1)
- [x] Silder in home page
- [x] Social network icons in footer
- [x] Better post list
- [x] Improved Admin UI

...and more improvements.

Feel free to tell me what you want in the next version!

**Comment by CberYellowstone** [comment]
尽量把css和js什么的合并一下?
(jQuery是真的卡)

**Comment by yrccondor** [comment]
@CberYellowstone 目前由于功能开关的需求，js 暂无法合并，而 css 本身只有一个主文件；去除 jquery 依赖正在进行中，不过由于相关功能较多，短时间内可能无法完全去除

**Comment by CberYellowstone** [comment]
> @CberYellowstone 目前由于功能开关的需求，js 暂无法合并，而 css 本身只有一个主文件；去除 jquery 依赖正在进行中，不过由于相关功能较多，短时间内可能无法完全去除

可以穷举出所有的开关可能然后每个可能一个js文件?(虽然我觉得工作量巨大)
这样就实现了单文件(当我没讲)
磁盘的占用可以不管

**Comment by yefoenix** [comment]
感谢您的开发工作！
想问一下，有没有可能增加 自定义主题颜色和强调颜色 的功能？

**Comment by yrccondor** [comment]
@yefoenix 短时间内可能不会，因为这牵扯到大量的 css 更改。但我已经在考虑这个功能都必要性了，所以在之后可能会加入

**Comment by yefoenix** [comment]
好的，再次感谢 @yrccondor ！

**Comment by jeeinn** [comment]
非常感谢提供主题👍！
再使用了几天后感觉有几点可以改良：

- 后台的设置页面建议可以再分出两个页面，现在的设置页太长了，需要滚动很久。
- 文章列表也希望能增加设置宽屏模式，让列表可以尽量宽一点
- 文末推荐文章，希望可以自定义文章数

**Comment by yrccondor** [comment]
@jeeinn 👌

**Comment by PiktCai** [comment]
感谢大佬的主题。请问能否改进一下网站公告的样式？目前发现除了简单样式的主页样式以外，其他两个样式中的网站公告都比较突兀，尤其在公告有比较长的一段时。

**Comment by yrccondor** [comment]
@PiktCai 可以的，我尽量优化下

**Comment by minibird** [comment]
这个主题真好！感谢作者的奉献！
在此报告错误。
环境信息如下：
centos7
Apache 2.4.6
mariadb 5.5.64
wordpress 5.4中文版
原主题：2019
已启用插件：Akismet Anti-Spam、Image Watermark、Rank Math SEO、StartWP Extended、SyntaxHighlighter Evolved、UpdraftPlus-备份/恢复、Watermark、Wordfence Security。
错误现象：
1、本来首页是最新的多篇文章，但启用主题后首页只显示了最新一篇的标题，内容无显示。
2、点击首页最新一篇文章的标题，报错提示”您的站点遇到了致命错误。“
3、MDx主题设置时，想更改首页图片，在媒体库中选择已经上传的图片时，无法选中。
4、启用了抽屉菜单，但是点击首页左上角的菜单图标，无任何反应，没有弹出抽屉菜单。
5、点击首页右上角搜索图片，无任何反应。

其他说明：其他主题运行正常。启用MDx后可以看到MDx主题的配置菜单。

**Comment by yrccondor** [comment]
@minibird 请新建 issue，并开启 PHP 错误输出查看是否有错误。目前猜测是你的 PHP 未启用 mb_strimwidth() 函数，请参考 https://doc.flyhigher.top/mdx/zh-CN/tech/php-errors/#mb_strimwidth

**Comment by minibird** [comment]
> 
> 
> @minibird 请新建 issue。
> 你可以开启 PHP 错误输出查看是否有错误。目前猜测是你的 PHP 未启用 `mb_strimwidth()` 函数，请参考 https://doc.flyhigher.top/mdx/zh-CN/tech/php-errors/#mb_strimwidth

谢谢您，真快啊！PHP版本7.2.27，我搜索了php.ini，没找到”;extension=mbstring“。只看到Dynamic Extension一类的设置参数，都注释掉未启用；还有[mbstring]下所有设置也被注释掉了。

**Comment by HertzHz** [comment]
大佬有增加pjax/ajax支持的想法吗

**Comment by yrccondor** [comment]
@HertzHz 暂时没有orz
目前我看到的 pjax 方案没有能做到完美的，就连 vue 的路由在一些情况下也会出小问题。我还是认为博客没有必要上 pjax

**Comment by Zxilly** [comment]
考虑添加post页面显示作者的功能吗？
如果博客是多人创作的，需要显示作者名

**Comment by yechs** [comment]
> 考虑添加post页面显示作者的功能吗？

@Zxilly 这个 feature 应该已经有了……？在每个 post 最后会显示作者名字、头像、简介
FYI, take a look at [this blog post](https://blog.shuye.dev/2019/10/hello-world/)

> 如果博客是多人创作的，需要显示作者名

如果是指一个博客中的不同博文由不同作者创作的话，应该现有的操作，在每篇博文最后显示作者就ok了？
如果是指同一篇博文有多个作者的话……似乎 WordPress 没有官方的支持，需要第三方的插件；可能还需要 MDx 适配一下第三方插件……？

**Comment by Zxilly** [comment]
> > 考虑添加post页面显示作者的功能吗？
> 
> @Zxilly 这个 feature 应该已经有了……？在每个 post 最后会显示作者名字、头像、简介
> FYI, take a look at [this blog post](https://blog.shuye.dev/2019/10/hello-world/)
> 
> > 如果博客是多人创作的，需要显示作者名
> 
> 如果是指一个博客中的不同博文由不同作者创作的话，应该现有的操作，在每篇博文最后显示作者就ok了？
> 如果是指同一篇博文有多个作者的话……似乎 WordPress 没有官方的支持，需要第三方的插件；可能还需要 MDx 适配一下第三方插件……？

我找到选项了，谢谢

**Comment by xkww3n** [comment]
是否考虑允许用户在WordPress控制台中设置mdx的js文件cdn地址以提高网页载入速度？

**Comment by yrccondor** [comment]
@xkww3n 已在 v2 中实现 (2f001f0)，但暂未发布 v2 更新，需要再过几星期
